spring:
  profiles:
    active: local

  jackson:
    property-naming-strategy: SNAKE_CASE

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 500
    generate-ddl: false
    hibernate:
      ddl-auto: validate

cloud:
  aws:
    credentials:
      instance-profile: true
    s3:
      bucket: matzip-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

matzip:
  jwt:
    secret: ~
