spring:
  profiles:
    active: local

  jackson:
    property-naming-strategy: SNAKE_CASE

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 500
        dialect: com.matzip.server.global.config.DialectConfig
    generate-ddl: false
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://localhost:3306/matzip_db
    username: matzip_admin
    password: MATZIP_admin_01

  redis:
    host: localhost
    port: 6379

cloud:
  aws:
    credentials:
      instance-profile: true
    s3:
      bucket: matzip-bucket-dev
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  secret: u7x!A%D*G-KaPdSgVkXp2s5v8y/B?E(H

---

spring:
  config:
    activate:
      on-profile: local

cloud:
  aws:
    credentials:
      instance-profile: false
      profile-name: my-aws
