# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java Spring Boot & Gradle CI

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Setup MySQL
      uses: samin/mysql-action@v1
      with:
        mysql database: 'matzip_db'
        mysql user: ${{ secrets.DB_USERNAME }}
        mysql password: ${{ secrets.DB_PASSWORD }}

    - name: Grant execution permission to gradlew
      run: chmod +x gradlew
      working-directory: server

    - name: Cache gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.g2
        key: ${{ runner.os }}-g2-${{ hashFiles('**/*.gradle*') }}
        restore-keys: ${{ runner.os }}-g2

    - name: Test with gradlew
      run: ./gradlew clean test --no-daemon
      working-directory: server
      env:
        DB_URL: jdbc:mysql://localhost:3306/matzip_db
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
